import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import readline from 'readline';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const envPath = path.join(__dirname, '.env');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function ask(question, defaultVal = '') {
  const suffix = defaultVal ? ` (${defaultVal})` : '';
  return new Promise((resolve) => {
    rl.question(`  ${question}${suffix}: `, (answer) => {
      resolve(answer.trim() || defaultVal);
    });
  });
}

async function main() {
  console.log(`
  ╔═══════════════════════════════════════════════╗
  ║           Claude Butler Setup Wizard          ║
  ║                                               ║
  ║  This will configure your personal AI butler  ║
  ║  to receive commands via Telegram.             ║
  ╚═══════════════════════════════════════════════╝
  `);

  // Check if .env already exists
  if (fs.existsSync(envPath)) {
    const overwrite = await ask('  .env already exists. Overwrite? (y/N)', 'N');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('\n  Setup cancelled. Your existing .env is unchanged.\n');
      rl.close();
      return;
    }
  }

  console.log('  ── Step 1: Telegram Bot ──');
  console.log('  Open Telegram, message @BotFather, send /newbot');
  console.log('  Follow the prompts and copy the token.\n');

  const botToken = await ask('Telegram Bot Token');
  if (!botToken) {
    console.log('\n  Bot token is required. Run setup again when ready.\n');
    rl.close();
    return;
  }

  console.log('\n  ── Step 2: Your User ID ──');
  console.log('  Message @userinfobot on Telegram to get your user ID.\n');

  const userId = await ask('Your Telegram User ID');
  if (!userId) {
    console.log('\n  User ID is required. Run setup again when ready.\n');
    rl.close();
    return;
  }

  console.log('\n  ── Step 3: Agent Settings ──\n');

  const maxConcurrent = await ask('Max concurrent agents', '2');
  const rateLimit = await ask('Max messages per minute', '10');
  const timeout = await ask('Agent timeout (seconds)', '300');

  console.log('\n  ── Step 4: Email Integration (optional) ──\n');

  const emailEnabled = await ask('Enable email integration? (y/N)', 'N');
  let gmailAddress = '';
  let gmailPassword = '';

  if (emailEnabled.toLowerCase() === 'y') {
    console.log('  Use a Gmail App Password (not your regular password).');
    console.log('  Google Account → Security → 2FA → App Passwords\n');
    gmailAddress = await ask('Gmail address');
    gmailPassword = await ask('Gmail App Password');
  }

  console.log('\n  ── Step 5: Claude CLI ──\n');

  const claudePath = await ask('Claude CLI path (leave blank for default)', 'claude');
  const defaultCwd = await ask('Default working directory', process.cwd());

  // Build .env content
  let env = `# Claude Butler Configuration\n`;
  env += `# Generated by setup wizard\n\n`;
  env += `# Telegram\n`;
  env += `TELEGRAM_BOT_TOKEN=${botToken}\n`;
  env += `ALLOWED_USER_IDS=${userId}\n\n`;
  env += `# Agent Settings\n`;
  env += `MAX_CONCURRENT_AGENTS=${maxConcurrent}\n`;
  env += `RATE_LIMIT_PER_MINUTE=${rateLimit}\n`;
  env += `AGENT_TIMEOUT_SECONDS=${timeout}\n\n`;

  if (gmailAddress) {
    env += `# Email\n`;
    env += `GMAIL_ADDRESS=${gmailAddress}\n`;
    env += `GMAIL_APP_PASSWORD=${gmailPassword}\n\n`;
  }

  env += `# Paths\n`;
  env += `CLAUDE_CLI_PATH=${claudePath}\n`;
  env += `DEFAULT_CWD=${defaultCwd}\n`;

  // Write .env
  fs.writeFileSync(envPath, env);

  // Ensure directories exist
  const dirs = ['skills', 'logs'];
  for (const dir of dirs) {
    const p = path.join(__dirname, dir);
    if (!fs.existsSync(p)) fs.mkdirSync(p, { recursive: true });
  }

  console.log(`
  ✅ Setup complete!

  Your .env has been written.

  Next steps:
    1. npm install         (install dependencies)
    2. npm start           (start the butler)
    3. Message your bot on Telegram!

  Add skills by creating directories in ./skills/
  See ./skills/_template/ for the skill format.

  `);

  rl.close();
}

main().catch((err) => {
  console.error('Setup failed:', err.message);
  rl.close();
  process.exit(1);
});
